# Generated by Django 3.2.7 on 2021-10-18 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_phone_brand_phone_feature_phone_feature_v_phone_modell'),
    ]

    operations = [
        migrations.CreateModel(
            name='tab_brand',
            fields=[
                ('tab_brand_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tab_brand_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tab_feature',
            fields=[
                ('tab_feature_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tab_feature_name', models.CharField(max_length=200)),
                ('tab_brand_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='device.tab_brand')),
            ],
        ),
        migrations.CreateModel(
            name='watch_brand',
            fields=[
                ('watch_brand_id', models.IntegerField(primary_key=True, serialize=False)),
                ('watch_brand_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='watch_feature',
            fields=[
                ('watch_feature_id', models.IntegerField(primary_key=True, serialize=False)),
                ('watch_feature_name', models.CharField(max_length=200)),
                ('watch_brand_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='device.watch_brand')),
            ],
        ),
        migrations.AddField(
            model_name='phone_modell',
            name='phone_Img',
            field=models.ImageField(default='static/images/phone.png', upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='watch_modell',
            fields=[
                ('watch_model_id', models.IntegerField(primary_key=True, serialize=False)),
                ('watch_model_name', models.CharField(max_length=200)),
                ('watch_Img', models.ImageField(default='static/images/phone.png', upload_to='uploads/')),
                ('watch_brand_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='device.watch_brand')),
            ],
        ),
        migrations.CreateModel(
            name='watch_feature_v',
            fields=[
                ('watch_feature_v_id', models.IntegerField(primary_key=True, serialize=False)),
                ('watch_feature_v_value', models.CharField(max_length=200)),
                ('watch_brand_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='device.watch_brand')),
                ('watch_feature_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='device.watch_feature')),
                ('watch_model_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='device.watch_modell')),
            ],
        ),
        migrations.CreateModel(
            name='tab_modell',
            fields=[
                ('tab_model_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tab_model_name', models.CharField(max_length=200)),
                ('tab_Img', models.ImageField(default='static/images/phone.png', upload_to='uploads/')),
                ('tab_brand_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='device.tab_brand')),
            ],
        ),
        migrations.CreateModel(
            name='tab_feature_v',
            fields=[
                ('tab_feature_v_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tab_feature_v_value', models.CharField(max_length=200)),
                ('tab_brand_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='device.tab_brand')),
                ('tab_feature_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='device.tab_feature')),
                ('tab_model_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='device.tab_modell')),
            ],
        ),
    ]
