# Generated by Django 3.2.7 on 2021-10-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20211017_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_modell',
            name='phone_Img',
            field=models.ImageField(default='static/images/phone.png', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='tab_modell',
            name='tab_Img',
            field=models.ImageField(default='static/images/phone.png', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='watch_modell',
            name='watch_Img',
            field=models.ImageField(default='static/images/phone.png', upload_to='uploads'),
        ),
    ]
