# Generated by Django 3.2.7 on 2021-10-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20211025_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_modell',
            name='phone_Img',
            field=models.ImageField(default='static/images/phone.png', upload_to='media'),
        ),
    ]
