# Generated by Django 3.2.7 on 2021-10-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_alter_phone_modell_phone_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_modell',
            name='phone_Img',
            field=models.ImageField(default='static/images/phone.png', upload_to='phoneimages'),
        ),
    ]
