# Generated by Django 3.2.7 on 2021-11-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_alter_phone_modell_phone_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('model_id', models.IntegerField(primary_key=True, serialize=False)),
                ('models_name', models.CharField(max_length=200)),
                ('img', models.ImageField(default='static/images/phone.png', upload_to='images')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
