# Generated by Django 3.2.7 on 2021-11-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
