# Generated by Django 3.2.7 on 2021-11-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.AlterField(
            model_name='tab_modell',
            name='tab_Img',
            field=models.ImageField(default='static/images/phone.png', upload_to='phoneimages'),
        ),
        migrations.AlterField(
            model_name='watch_modell',
            name='watch_Img',
            field=models.ImageField(default='static/images/phone.png', upload_to='phoneimages'),
        ),
    ]
